=== iConsult2000/BaseDeConnaissance/XML_SCHEMA_BIBLIO/Bibliographie/biblio.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="ARTICLES" type="_ARTICLES"/>
	
	<xsd:complexType name="_ARTICLES">
		<xsd:sequence>
			<xsd:element name="ARTICLE" type="_ARTICLE" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="_ARTICLE">
		<xsd:sequence>
			<xsd:element name="TITRE" type="xsd:string"/>
			<xsd:element name="TEXTE" type="_TEXTE"/>
			<xsd:element name="DATE" type="xsd:gYear"/>
			<xsd:element name="BIBLIOGRAPHIE" type="_BIBLIO"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="_TEXTE" mixed="true">
		<xsd:sequence>
			<xsd:element name="PARAGRAPHE" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="_BIBLIO">
		<xsd:choice>
			<xsd:element name="SITE" type="_SITE"/>
			<xsd:element name="OUVRAGE" type="_OUVRAGE"/>
		</xsd:choice>
	</xsd:complexType>
	
	<xsd:complexType name="_SITE">
		<xsd:sequence>
			<xsd:element name="NOM" type="xsd:string"/>
			<xsd:element name="URL" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="_OUVRAGE">
		<xsd:sequence>
			<xsd:element name="TITRE" type="xsd:string"/>
			<xsd:element name="AUTEUR" type="xsd:string"/>
			<xsd:element name="DATE" type="xsd:date"/>
			<xsd:element name="EDITEUR" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== iConsult2000/BaseDeConnaissance/XML_SCHEMA_BIBLIO/Bibliographie/biblio.xml
<?xml version="1.0" encoding="UTF-8"?>
<ARTICLES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblio.xsd">
  <ARTICLE>
    <TITRE>TITRE</TITRE>
    <TEXTE>
    JE SUIS SUPERBE
      <PARAGRAPHE>PARAGRAPHE</PARAGRAPHE>
    </TEXTE>
    <DATE>2001</DATE>
    <BIBLIOGRAPHIE>
      <!--<SITE>
        <NOM>NOM</NOM>
        <URL>URL</URL>
      </SITE>-->
      <OUVRAGE>
        <TITRE>NOM</TITRE>
        <AUTEUR>URL</AUTEUR>
        <DATE>2012-03-02</DATE>
        <EDITEUR></EDITEUR>
      </OUVRAGE>
    </BIBLIOGRAPHIE>
  </ARTICLE>
</ARTICLES>
